name: Fetch Composite Secret from AWS Secrets Manager

on: [push]

jobs:
  fetch-secret:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::577638356286:role/compositegit
        aws-region: us-east-1

    - name: Install AWS CLI
      run: sudo apt-get install -y awscli

    - name: Fetch secret from AWS Secrets Manager
      id: fetch-secret
      run: |
        aws secretsmanager get-secret-value --secret-id comp-secret --region us-east-1 --query SecretString --output text > secret.json

    - name: Parse and Use Secrets
      run: |
        dbUsername=$(cat secret.json | jq -r '.dbUsername')
        dbPassword=$(cat secret.json | jq -r '.dbPassword')
        apiKey=$(cat secret.json | jq -r '.apiKey')
        echo "dbUsername: $dbUsername"
        echo "dbPassword: $dbPassword"
        echo "apiKey: $apiKey"
