name: AWS Secrets Manager Integration
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::577638356286:role/GitHubActionsSecretsRole
        aws-region: us-east-1

    - name: Fetch Build Process Secrets
      id: fetch-build-secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: "mule/BuildArtifacts"  
        parse-json-secrets: true           

    - name: Print the fetched secrets
      run: |
        echo "Using Build Process Secrets"
        
        # Print the entire output to see what is returned
        echo "Build Process Secrets: ${{ steps.fetch-build-secrets.outputs.SECRET_STRING }}"
        
        # If the secret is in JSON format, you can parse it
        # Use jq to parse and print each key of the JSON object
        echo "Parsed secrets using jq:"
        echo "${{ steps.fetch-build-secrets.outputs.SECRET_STRING }}" | jq .  # This will print the entire object

        # You can access specific keys like so:
        echo "NEXUS_PASS: ${{ steps.fetch-build-secrets.outputs.MULE_BUILDARTIFACTS_NEXUS_PASS }}"
        echo "SNAPSHOT_PASS: ${{ steps.fetch-build-secrets.outputs.MULE_BUILDARTIFACTS_SNAPSHOT_PASS }}"
        echo "EXCHANGE_PASSWORD: ${{ steps.fetch-build-secrets.outputs.MULE_BUILDARTIFACTS_EXCHANGE_PASSWORD }}"
   

    - name: Fetch Deployment Process Secrets
      id: fetch-deploy-secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-id: dev/mule/creds
        parse-json-secrets: true

    - name: Print Deployment Process Secrets
      run: |
        echo "CONNECTEDAPP_CLIENTID=${{ steps.fetch-deploy-secrets.outputs.CONNECTEDAPP_CLIENTID }}"
        echo "CONNECTEDAPP_CLIENT_SECRET=${{ steps.fetch-deploy-secrets.outputs.CONNECTEDAPP_CLIENT_SECRET }}"
        echo "ANYPOINT_PLATFORM_CLIENT_ID=${{ steps.fetch-deploy-secrets.outputs.ANYPOINT_PLATFORM_CLIENT_ID }}"
        echo "ANYPOINT_PLATFORM_CLIENT_SECRET=${{ steps.fetch-deploy-secrets.outputs.ANYPOINT_PLATFORM_CLIENT_SECRET }}"
        echo "CDC_LOGGING_SERVICE_TOKEN=${{ steps.fetch-deploy-secrets.outputs.CDC_LOGGING_SERVICE_TOKEN }}"
        echo "CONFIGSERVER_PASSWORD=${{ steps.fetch-deploy-secrets.outputs.CONFIGSERVER_PASSWORD }}"
        echo "LOGGING_SERVICE_TOKEN=${{ steps.fetch-deploy-secrets.outputs.LOGGING_SERVICE_TOKEN }}"
