name: AWS Secrets Manager Integration

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::577638356286:role/GitHubActionsSecretsRole
        aws-region: us-east-1

    - name: Fetch Build Process Secrets
      id: fetch-build-secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-id: mule/BuildArtifacts

    - name: Print Build Process Secrets
      run: |
        echo "NEXUS_PASS=${{ steps.fetch-build-secrets.outputs.NEXUS_PASS }}"
        echo "SNAPSHOT_PASS=${{ steps.fetch-build-secrets.outputs.SNAPSHOT_PASS }}"
        echo "EXCHANGE_PASSWORD=${{ steps.fetch-build-secrets.outputs.EXCHANGE_PASSWORD }}"

    - name: Fetch Deployment Process Secrets
      id: fetch-deploy-secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-id: dev/mule/creds

    - name: Print Deployment Process Secrets
      run: |
        echo "CONNECTEDAPP_CLIENTID=${{ steps.fetch-deploy-secrets.outputs.CONNECTEDAPP_CLIENTID }}"
        echo "CONNECTEDAPP_CLIENT_SECRET=${{ steps.fetch-deploy-secrets.outputs.CONNECTEDAPP_CLIENT_SECRET }}"
        echo "ANYPOINT_PLATFORM_CLIENT_ID=${{ steps.fetch-deploy-secrets.outputs.ANYPOINT_PLATFORM_CLIENT_ID }}"
        echo "ANYPOINT_PLATFORM_CLIENT_SECRET=${{ steps.fetch-deploy-secrets.outputs.ANYPOINT_PLATFORM_CLIENT_SECRET }}"
        echo "CDC_LOGGING_SERVICE_TOKEN=${{ steps.fetch-deploy-secrets.outputs.CDC_LOGGING_SERVICE_TOKEN }}"
        echo "CONFIGSERVER_PASSWORD=${{ steps.fetch-deploy-secrets.outputs.CONFIGSERVER_PASSWORD }}"
        echo "LOGGING_SERVICE_TOKEN=${{ steps.fetch-deploy-secrets.outputs.LOGGING_SERVICE_TOKEN }}"
